## Day 5 

<pre>Numpy : 'Numerical Python' <b>
     Numpy is a python library which is used to perform different mathematical operations on arrays . 
     Array is denoted with '[ ]'. its ordered , mutable and homegeneous collection of data.
</pre>

In [1]:
import numpy as np

In [9]:
np.__version__

'2.3.5'

### 1D Array

In [13]:
# List to array
a = np.array([2,5,8,1,90])
a

array([ 2,  5,  8,  1, 90])

In [23]:
b = np.array([[12,10.7,82,19,12.5]])
b

array([[12. , 10.7, 82. , 19. , 12.5]])

In [29]:
a = np.array([25,'aplle', 2.5, True],dtype='<U3')
a

# it converts all the datatypes into str b/c it has most priority.
# priority : str, complex, float, int , bool

array(['25', 'apl', '2.5', 'Tru'], dtype='<U3')

In [27]:
a = np.array([25,  True])
a

array([25,  1])

In [30]:
#### Tuple to array
t = np.array((10,20,35,25,40))
t

array([10, 20, 35, 25, 40])

In [32]:
### Set to array
s = np.array({20,10,25,39,35})
s

array({35, 20, 39, 25, 10}, dtype=object)

In [34]:
## dictionary to array
d = np.array({'a' : 1, 'b':2 , 'c' : 3})
d

array({'a': 1, 'b': 2, 'c': 3}, dtype=object)

In [35]:
type(d)

numpy.ndarray

### 2D Array

In [38]:
# Creating 2D array
a = np.array([ [1,2,3], 
               [4,5,6], 
               [7,8,9] 
])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
a = np.array([ (1,2,3), 
               (4,5,6)
])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
a1 = np.array([ {1,2,3}, 
               {4,5,6}
])
a1

array([{1, 2, 3}, {4, 5, 6}], dtype=object)

#### Array Attributes : 

In [43]:
b = np.array([ [1,3,2,4], 
               [1,5,3,8],
               [4,3,6,7]
])
b

array([[1, 3, 2, 4],
       [1, 5, 3, 8],
       [4, 3, 6, 7]])

In [44]:
b.shape

(3, 4)

In [45]:
b.size

12

In [47]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)

    Create an array.

    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        ``__array__`` method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array. If not given, NumPy will try to use
        a default ``dtype`` that can represent the values (by applying promotion
        rules when necessary.)
    copy : bool, optional
        If ``True`` (default), then the array data is copied. If ``None``,
        a copy will only be made if ``__array__`` returns a copy, if obj is
        a nested sequence, or if a copy is needed to satisfy any of the other
        requirements (``dtype``, ``order``, 

In [48]:
b.ndim

2

In [49]:
help(np.ndim)

Help on _ArrayFunctionDispatcher in module numpy:

ndim(a)
    Return the number of dimensions of an array.

    Parameters
    ----------
    a : array_like
        Input array.  If it is not already an ndarray, a conversion is
        attempted.

    Returns
    -------
    number_of_dimensions : int
        The number of dimensions in `a`.  Scalars are zero-dimensional.

    See Also
    --------
    ndarray.ndim : equivalent method
    shape : dimensions of array
    ndarray.shape : dimensions of array

    Examples
    --------
    >>> import numpy as np
    >>> np.ndim([[1,2,3],[4,5,6]])
    2
    >>> np.ndim(np.array([[1,2,3],[4,5,6]]))
    2
    >>> np.ndim(1)
    0



In [57]:
c = np.array([[[[[[1,3,4]]]]]])
c.ndim

6

In [66]:
m = np.array([1,2,3],ndmin=45)
m

array([[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[1,
                                                   2,
                                                   3]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]])

In [67]:
print(np.MAXDIMS)

AttributeError: module 'numpy' has no attribute 'MAXDIMS'

In [68]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [69]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [70]:
np.zeros(6,dtype=int)

array([0, 0, 0, 0, 0, 0])

In [81]:
np.ones((4,5), dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [84]:
np.full((5,6),2)

array([[2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2]])

In [85]:
np.full((5,6),'*')

array([['*', '*', '*', '*', '*', '*'],
       ['*', '*', '*', '*', '*', '*'],
       ['*', '*', '*', '*', '*', '*'],
       ['*', '*', '*', '*', '*', '*'],
       ['*', '*', '*', '*', '*', '*']], dtype='<U1')

### Identity Matrix : 

In [88]:
np.eye(6,dtype=int)

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1]])

In [92]:
help(np.linspace)

Help on _ArrayFunctionDispatcher in module numpy:

linspace(
    start,
    stop,
    num=50,
    endpoint=True,
    retstep=False,
    dtype=None,
    axis=0,
    *,
    device=None
)
    Return evenly spaced numbers over a specified interval.

    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].

    The endpoint of the interval can optionally be excluded.

    .. versionchanged:: 1.20.0
        Values are rounded towards ``-inf`` instead of ``0`` when an
        integer ``dtype`` is specified. The old behavior can
        still be obtained with ``np.linspace(start, stop, num).astype(int)``

    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that `stop` is excluded.  Note that the step
        

In [93]:
np.linspace(1,6,6)

array([1., 2., 3., 4., 5., 6.])

In [99]:
np.linspace(1,100,11)

array([  1. ,  10.9,  20.8,  30.7,  40.6,  50.5,  60.4,  70.3,  80.2,
        90.1, 100. ])

In [100]:
np.random.rand()

0.2096981437097306

In [108]:
np.random.rand(4)*100

array([52.65268158,  7.85716705, 64.16138958, 90.49726895])

In [109]:
## Creating 2D array 
np.random.rand(3,4)

array([[0.53196401, 0.35030669, 0.9248773 , 0.2515328 ],
       [0.98493992, 0.04665122, 0.72674605, 0.42322057],
       [0.1377739 , 0.39459844, 0.22533931, 0.64124827]])

In [123]:
np.random.randint(1,10)

7

In [125]:
np.random.randint(1,100,6)

array([85, 91, 48, 83, 95, 20], dtype=int32)

In [128]:
np.random.randint(1,100,(7,8))

array([[14, 48, 83, 43, 18, 46, 35, 23],
       [89, 12, 54, 31, 40, 26, 63, 47],
       [58, 78,  5, 32, 23, 65, 47, 48],
       [55, 21, 18, 41, 14, 56, 64, 37],
       [55,  2, 57, 62, 67, 32,  9, 71],
       [70, 45, 61, 42, 39,  5, 56,  7],
       [54, 35, 16, 34,  8, 19, 39,  9]], dtype=int32)

### Mathematical Functions : 

In [131]:
a = np.array([23,75,67,48,80])
b = np.array([2,5,8,6,7])
print(a)
print(b)

[23 75 67 48 80]
[2 5 8 6 7]


In [134]:
np.add(a,b)

array([25, 80, 75, 54, 87])

In [135]:
np.subtract(a,b)

array([21, 70, 59, 42, 73])

In [137]:
np.multiply(a,b)

array([ 46, 375, 536, 288, 560])

In [139]:
np.divide(a,b)

array([11.5       , 15.        ,  8.375     ,  8.        , 11.42857143])

In [141]:
np.floor_divide(a,b)

array([11, 15,  8,  8, 11])

In [142]:
np.remainder(a,b)

array([1, 0, 3, 0, 3])

In [143]:
np.mod(a,b)

array([1, 0, 3, 0, 3])

In [144]:
np.divmod(a,b)

(array([11, 15,  8,  8, 11]), array([1, 0, 3, 0, 3]))

In [145]:
np.log(a)

array([3.13549422, 4.31748811, 4.20469262, 3.87120101, 4.38202663])

In [146]:
np.sqrt(a)

array([4.79583152, 8.66025404, 8.18535277, 6.92820323, 8.94427191])

In [147]:
np.cbrt(a)

array([2.84386698, 4.21716333, 4.0615481 , 3.63424119, 4.30886938])

In [148]:
np.power(b,2)

array([ 4, 25, 64, 36, 49])

In [149]:
np.sin(a)

array([-0.8462204 , -0.38778164, -0.85551998, -0.76825466, -0.99388865])

In [150]:
np.pi

3.141592653589793

In [154]:
# in radians
np.sin(80)

np.float64(-0.9938886539233752)

In [158]:
# in degrees
np.sin(180*(180/np.pi))

np.float64(0.5715301650260188)

In [160]:
np.cos(a)

array([-0.53283302,  0.92175127, -0.5177698 , -0.64014434, -0.11038724])

In [161]:
np.tan(a)

array([ 1.58815308, -0.42070095,  1.65231726,  1.20012724,  9.00365495])

In [162]:
1/np.tan(a)

array([ 0.62966222, -2.37698536,  0.60521065,  0.83324498,  0.11106601])

### Statistical Function : 

In [164]:
a = np.array([45,67,20,58,25])
a

array([45, 67, 20, 58, 25])

In [165]:
np.max(a)

np.int64(67)

In [166]:
np.min(a)

np.int64(20)

In [167]:
np.std(a)

np.float64(18.20988742414406)

In [168]:
## index position of the max
np.argmax(a)

np.int64(1)

In [169]:
np.argmin(a)

np.int64(2)

In [170]:
np.sort(a)

array([20, 25, 45, 58, 67])

In [171]:
# index position of origin
np.argsort(a)

array([2, 4, 0, 3, 1])

In [174]:
# reverse of the sequence
np.flip(a)

array([25, 58, 20, 67, 45])

In [175]:
np.flip(np.sort(a))

array([67, 58, 45, 25, 20])

In [176]:
np.mean(a)

np.float64(43.0)

In [177]:
np.median(a)

np.float64(45.0)

In [179]:
b = np.array([45,67,20,58,25,21])
np.median(b)

np.float64(35.0)

In [180]:
np.var(a)

np.float64(331.6)

In [181]:
#  cumulative_sum 
np.cumsum(a)

array([ 45, 112, 132, 190, 215])

In [184]:
np.cumprod(a)

array([      45,     3015,    60300,  3497400, 87435000])

In [186]:
a = np.array([1,2,3,4])
np.repeat(a,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4])

In [188]:
np.tile(a,4)

array([1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4])

In [189]:
a = np.array([1,2,3,4,7,4,1,4,5,4,4,8,4])
np.where(a==4)

(array([ 3,  5,  7,  9, 10, 12]),)

In [191]:
round(np.round(25.6))

26

In [193]:
np.round(25.5)

np.float64(26.0)

In [192]:
np.ceil(25.2)

np.float64(26.0)

In [194]:
np.floor(25.8)

np.float64(25.0)

In [196]:
np.trunc(25.8)

np.float64(25.0)