## Day 5 

<pre>Numpy : 'Numerical Python' <b>
     Numpy is a python library which is used to perform different mathematical operations on arrays . 
     Array is denoted with '[ ]'. its ordered , mutable and homegeneous collection of data.
</pre>

In [24]:
import numpy as np

In [25]:
np.__version__

'2.3.5'

### 1D Array

In [26]:
# List to array
a = np.array([2,5,8,1,90])
a

array([ 2,  5,  8,  1, 90])

In [27]:
b = np.array([[12,10.7,82,19,12.5]])
b

array([[12. , 10.7, 82. , 19. , 12.5]])

In [28]:
a = np.array([25,'aplle', 2.5, True],dtype='<U3')
a

# it converts all the datatypes into str b/c it has most priority.
# priority : str, complex, float, int , bool

array(['25', 'apl', '2.5', 'Tru'], dtype='<U3')

In [29]:
a = np.array([25,  True])
a

array([25,  1])

In [30]:
#### Tuple to array
t = np.array((10,20,35,25,40))
t

array([10, 20, 35, 25, 40])

In [31]:
### Set to array
s = np.array({20,10,25,39,35})
s

array({35, 20, 39, 25, 10}, dtype=object)

In [32]:
## dictionary to array
d = np.array({'a' : 1, 'b':2 , 'c' : 3})
d

array({'a': 1, 'b': 2, 'c': 3}, dtype=object)

In [33]:
type(d)

numpy.ndarray

### 2D Array

In [34]:
# Creating 2D array
a = np.array([ [1,2,3], 
               [4,5,6], 
               [7,8,9] 
])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
a = np.array([ (1,2,3), 
               (4,5,6)
])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
a1 = np.array([ {1,2,3}, 
               {4,5,6}
])
a1

array([{1, 2, 3}, {4, 5, 6}], dtype=object)

#### Array Attributes : 

In [37]:
b = np.array([ [1,3,2,4], 
               [1,5,3,8],
               [4,3,6,7]
])
b

array([[1, 3, 2, 4],
       [1, 5, 3, 8],
       [4, 3, 6, 7]])

In [38]:
b.shape

(3, 4)

In [39]:
b.size

12

In [40]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)

    Create an array.

    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        ``__array__`` method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array. If not given, NumPy will try to use
        a default ``dtype`` that can represent the values (by applying promotion
        rules when necessary.)
    copy : bool, optional
        If ``True`` (default), then the array data is copied. If ``None``,
        a copy will only be made if ``__array__`` returns a copy, if obj is
        a nested sequence, or if a copy is needed to satisfy any of the other
        requirements (``dtype``, ``order``, 

In [41]:
b.ndim

2

In [42]:
help(np.ndim)

Help on _ArrayFunctionDispatcher in module numpy:

ndim(a)
    Return the number of dimensions of an array.

    Parameters
    ----------
    a : array_like
        Input array.  If it is not already an ndarray, a conversion is
        attempted.

    Returns
    -------
    number_of_dimensions : int
        The number of dimensions in `a`.  Scalars are zero-dimensional.

    See Also
    --------
    ndarray.ndim : equivalent method
    shape : dimensions of array
    ndarray.shape : dimensions of array

    Examples
    --------
    >>> import numpy as np
    >>> np.ndim([[1,2,3],[4,5,6]])
    2
    >>> np.ndim(np.array([[1,2,3],[4,5,6]]))
    2
    >>> np.ndim(1)
    0



In [43]:
c = np.array([[[[[[1,3,4]]]]]])
c.ndim

6

In [44]:
m = np.array([1,2,3],ndmin=45)
m

array([[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[1,
                                                   2,
                                                   3]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]])

In [45]:
print(np.MAXDIMS)

AttributeError: module 'numpy' has no attribute 'MAXDIMS'

In [46]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [47]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [48]:
np.zeros(6,dtype=int)

array([0, 0, 0, 0, 0, 0])

In [49]:
np.ones((4,5), dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [50]:
np.full((5,6),2)

array([[2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2]])

In [51]:
np.full((5,6),'*')

array([['*', '*', '*', '*', '*', '*'],
       ['*', '*', '*', '*', '*', '*'],
       ['*', '*', '*', '*', '*', '*'],
       ['*', '*', '*', '*', '*', '*'],
       ['*', '*', '*', '*', '*', '*']], dtype='<U1')

### Identity Matrix : 

In [52]:
np.eye(6,dtype=int)

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1]])

In [53]:
help(np.linspace)

Help on _ArrayFunctionDispatcher in module numpy:

linspace(
    start,
    stop,
    num=50,
    endpoint=True,
    retstep=False,
    dtype=None,
    axis=0,
    *,
    device=None
)
    Return evenly spaced numbers over a specified interval.

    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].

    The endpoint of the interval can optionally be excluded.

    .. versionchanged:: 1.20.0
        Values are rounded towards ``-inf`` instead of ``0`` when an
        integer ``dtype`` is specified. The old behavior can
        still be obtained with ``np.linspace(start, stop, num).astype(int)``

    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that `stop` is excluded.  Note that the step
        

In [54]:
np.linspace(1,6,6)

array([1., 2., 3., 4., 5., 6.])

In [55]:
np.linspace(1,100,11)

array([  1. ,  10.9,  20.8,  30.7,  40.6,  50.5,  60.4,  70.3,  80.2,
        90.1, 100. ])

In [56]:
np.random.rand()

0.8272923886716935

In [57]:
np.random.rand(4)*100

array([50.69356457, 15.12194827, 62.92807089, 94.96831303])

In [58]:
## Creating 2D array 
np.random.rand(3,4)

array([[0.65085547, 0.11883723, 0.39428356, 0.657696  ],
       [0.18007495, 0.88097169, 0.42272522, 0.14023405],
       [0.3997849 , 0.87479911, 0.95163363, 0.73350595]])

In [59]:
np.random.randint(1,10)

1

In [60]:
np.random.randint(1,100,6)

array([15, 65, 90, 50, 88, 91], dtype=int32)

In [61]:
np.random.randint(1,100,(7,8))

array([[50, 85, 77, 97, 19, 73, 47, 64],
       [18, 18, 90, 75, 37, 80, 85, 77],
       [10,  1, 32, 16, 25, 57, 18, 44],
       [52, 46, 16, 41, 90, 30, 86, 83],
       [85, 72, 96, 55,  8, 76, 27, 94],
       [27, 37, 61, 48, 12,  8,  1, 43],
       [48, 81, 76, 67, 27, 82, 58, 85]], dtype=int32)

### Mathematical Functions : 

In [62]:
a = np.array([23,75,67,48,80])
b = np.array([2,5,8,6,7])
print(a)
print(b)

[23 75 67 48 80]
[2 5 8 6 7]


In [63]:
np.add(a,b)

array([25, 80, 75, 54, 87])

In [64]:
np.subtract(a,b)

array([21, 70, 59, 42, 73])

In [65]:
np.multiply(a,b)

array([ 46, 375, 536, 288, 560])

In [66]:
np.divide(a,b)

array([11.5       , 15.        ,  8.375     ,  8.        , 11.42857143])

In [67]:
np.floor_divide(a,b)

array([11, 15,  8,  8, 11])

In [68]:
np.remainder(a,b)

array([1, 0, 3, 0, 3])

In [69]:
np.mod(a,b)

array([1, 0, 3, 0, 3])

In [70]:
np.divmod(a,b)

(array([11, 15,  8,  8, 11]), array([1, 0, 3, 0, 3]))

In [71]:
np.log(a)

array([3.13549422, 4.31748811, 4.20469262, 3.87120101, 4.38202663])

In [72]:
np.sqrt(a)

array([4.79583152, 8.66025404, 8.18535277, 6.92820323, 8.94427191])

In [73]:
np.cbrt(a)

array([2.84386698, 4.21716333, 4.0615481 , 3.63424119, 4.30886938])

In [74]:
np.power(b,2)

array([ 4, 25, 64, 36, 49])

In [75]:
np.sin(a)

array([-0.8462204 , -0.38778164, -0.85551998, -0.76825466, -0.99388865])

In [76]:
np.pi

3.141592653589793

In [77]:
# in radians
np.sin(80)

np.float64(-0.9938886539233752)

In [78]:
# in degrees
np.sin(180*(180/np.pi))

np.float64(0.5715301650260188)

In [79]:
np.cos(a)

array([-0.53283302,  0.92175127, -0.5177698 , -0.64014434, -0.11038724])

In [80]:
np.tan(a)

array([ 1.58815308, -0.42070095,  1.65231726,  1.20012724,  9.00365495])

In [81]:
1/np.tan(a)

array([ 0.62966222, -2.37698536,  0.60521065,  0.83324498,  0.11106601])

### Statistical Function : 

In [82]:
a = np.array([45,67,20,58,25])
a

array([45, 67, 20, 58, 25])

In [83]:
np.max(a)

np.int64(67)

In [84]:
np.min(a)

np.int64(20)

In [85]:
np.std(a)

np.float64(18.20988742414406)

In [86]:
## index position of the max
np.argmax(a)

np.int64(1)

In [87]:
np.argmin(a)

np.int64(2)

In [88]:
np.sort(a)

array([20, 25, 45, 58, 67])

In [89]:
# index position of origin
np.argsort(a)

array([2, 4, 0, 3, 1])

In [90]:
# reverse of the sequence
np.flip(a)

array([25, 58, 20, 67, 45])

In [91]:
np.flip(np.sort(a))

array([67, 58, 45, 25, 20])

In [92]:
np.mean(a)

np.float64(43.0)

In [93]:
np.median(a)

np.float64(45.0)

In [94]:
b = np.array([45,67,20,58,25,21])
np.median(b)

np.float64(35.0)

In [95]:
np.var(a)

np.float64(331.6)

In [96]:
#  cumulative_sum 
np.cumsum(a)

array([ 45, 112, 132, 190, 215])

In [97]:
np.cumprod(a)

array([      45,     3015,    60300,  3497400, 87435000])

In [98]:
a = np.array([1,2,3,4])
np.repeat(a,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4])

In [99]:
np.tile(a,4)

array([1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4])

In [100]:
a = np.array([1,2,3,4,7,4,1,4,5,4,4,8,4])
np.where(a==4)

(array([ 3,  5,  7,  9, 10, 12]),)

In [101]:
round(np.round(25.6))

26

In [102]:
np.round(25.5)

np.float64(26.0)

In [103]:
np.ceil(25.2)

np.float64(26.0)

In [104]:
np.floor(25.8)

np.float64(25.0)

In [105]:
np.trunc(25.8)

np.float64(25.0)

## Day 8 

### Vector maths

In [106]:
a = np.array([[1,3],[2,4]])
b = np.array([[5,7],[6,8]])

print(a)
print(b)

[[1 3]
 [2 4]]
[[5 7]
 [6 8]]


In [107]:
## dot product
np.dot(a,b)

array([[23, 31],
       [34, 46]])

In [108]:
## Cross product
np.cross(a,b)

C:\Users\KIIT\AppData\Local\Temp\ipykernel_23836\3154159301.py:2: DeprecationWarning: Arrays of 2-dimensional vectors are deprecated. Use arrays of 3-dimensional vectors instead. (deprecated in NumPy 2.0)
  np.cross(a,b)


array([-8, -8])

In [109]:
# Transpose converts rows into columns, and columns into row
np.transpose(a)

array([[1, 2],
       [3, 4]])

In [111]:
# another way to do transpose 
a.T

array([[1, 2],
       [3, 4]])

In [113]:
a = np.array([45,76,28,89,76,20])
a

array([45, 76, 28, 89, 76, 20])

In [114]:
## Indexing
a[4]

np.int64(76)

In [115]:
a[-3]

np.int64(89)

In [118]:
## Slicing : syntax for 1D array :  var[start : stop +1 : step ]
a[2:5:1]

array([28, 89, 76])

In [125]:
b = np.random.randint(1,10,(6,6))
b

array([[9, 1, 6, 3, 8, 3],
       [7, 1, 4, 6, 1, 1],
       [9, 8, 3, 3, 8, 1],
       [8, 7, 7, 6, 7, 8],
       [4, 2, 3, 3, 3, 5],
       [6, 7, 6, 4, 4, 5]], dtype=int32)

In [120]:
### Indexing in 2D array : syntax : var[ row_index, column_index ]
b[1,3]

np.int32(2)

In [121]:
## Slicing in 2D array : syntax : var[row_slicing, column_slicing ] 
b[1:3:1,1:5:1]

array([[ 1, 11,  2,  3],
       [ 9,  9, 11,  3]], dtype=int32)

In [122]:
b[2:5:2,1:6:2]

array([[ 9, 11, 16],
       [19, 12,  6]], dtype=int32)

In [126]:
np.where(b==3)

(array([0, 0, 2, 2, 4, 4, 4]), array([3, 5, 2, 3, 2, 3, 4]))

In [127]:
# Concatenation - joing the matrix
a = np.random.randint(1,20,(2,2))
a

array([[ 4, 15],
       [ 5,  7]], dtype=int32)

In [128]:
b = np.random.randint(1,20,(2,4))
b

array([[ 3,  2,  4,  9],
       [ 3,  4, 11, 12]], dtype=int32)

In [129]:
c = np.random.randint(1,20,(4,4))
c

array([[15, 18,  9, 19],
       [ 4,  8, 17, 18],
       [ 3, 11,  2,  1],
       [15, 14, 13, 18]], dtype=int32)

In [132]:
np.concatenate((a,b),axis=1)

array([[ 4, 15,  3,  2,  4,  9],
       [ 5,  7,  3,  4, 11, 12]], dtype=int32)

In [133]:
np.concatenate((b,c))

array([[ 3,  2,  4,  9],
       [ 3,  4, 11, 12],
       [15, 18,  9, 19],
       [ 4,  8, 17, 18],
       [ 3, 11,  2,  1],
       [15, 14, 13, 18]], dtype=int32)

In [134]:
d = np.random.randint(1,20,(2,2))
d

array([[17,  3],
       [11, 12]], dtype=int32)

In [135]:
np.stack((a,d),axis=1)

array([[[ 4, 15],
        [17,  3]],

       [[ 5,  7],
        [11, 12]]], dtype=int32)